POST http://localhost:8081/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxIiwiZXhwIjoxNzY3NjQ3MjE4LCJ1c2VySWQiOjExfQ.EFuGS30mZp7XmbzlfiiatBAtYgZb26sPVbgzh1zNXSM

{
    "name": "hello kdkk ",
    "description": "A test event",
    "location": "Hawkins",
    "dateTime": "2025-01-01T21:00:00.000Z"

}